FROM golang:1.15-alpine3.12 as builder
WORKDIR /root/
RUN apk add --no-cache git
RUN go get github.com/johnnylin-a/go-wol/cmd/wol
RUN go build github.com/johnnylin-a/go-wol/cmd/wol

FROM php:8.0-fpm-alpine3.12
WORKDIR /home/www-data/
COPY --from=builder /root/wol .
RUN chmod 755 ./wol